### ISSUE TITLE
Gravatar for info@rdoc.info

### ISSUE THREAD

**Issue by jeffrafter** [zapnap/rdocinfo#15]
We must be cool. I am thinking an octocat in reading glasses. Can we do that?

http://github.com/images/modules/training/octocat_professor.png

We could also set this up for github@rdoc.info and then just fix up the docs user profile.

**Comment by zapnap** [comment]
My only concern would be 'infringing' on the GitHub logo. I'll use cthulhu for now, but we can change him out later if you want (maybe after confirming with the GitHub guys)

**Comment by jeffrafter** [comment]
Seriously? I mean, they gave us the go ahead on infringing I thought. I think that the octoprofessor would be the least of our worries :)

**Comment by zapnap** [comment]
Jeff doesn't seem to think this will be a prob after talking with Chris and Tom at Railsconf. I've gone ahead and added it :).
