### ISSUE TITLE
GitHub pages generation redirects wrong

### ISSUE THREAD

**Issue by jeffrafter** [zapnap/rdocinfo#18]
If you generate documentation for a project which already exists (e.g. brynary/webrat) it will correctly post to /projects on rdocinfo and start generating docs for the latest commit. However, the params[:return] url does not indicate the commit_hash it is waiting on, only owner and name. Because of this when the jQuery on the generate/index.html checks to see if it is available, it immediately finds docs.github.com/brynary/webrat/index.html which redirects to the existing version, not the latest version.

**Comment by jeffrafter** [comment]
Becuase there is not a good way to update to the latest revision from the GH pages anyway, this will not be encountered very often and can wait.

**Comment by zapnap** [comment]
shelved for now as docs.github.com has been temporarily disabled (due to page sync issues)
