### ISSUE TITLE
Include the project name in the title tag

### ISSUE THREAD

**Issue by skateinmars** [zapnap/rdocinfo#19]
The title meta tag for a given project contains only "rdoc.info" at the moment.
When browsing a project (ex. http://rdoc.info/projects/thoughtbot/shoulda ) the project owner and name should be included in the title.

For example, this could be <title>capistrano/capistrano - rdoc.info</title>.

This would be useful when opening multiple documentation pages within different tabs.

**Comment by zapnap** [comment]
fixed this awhile ago :)

**Comment by skateinmars** [comment]
I saw this a little while after reporting, thanks !
(sorry I forgot to close the ticket)
