### ISSUE TITLE
Docs on github don't seem to get updated

### ISSUE THREAD

**Issue by bkerley** [zapnap/rdocinfo#20]
http://docs.github.com/bkerley/affine/ redirects to a much older version than is visible at http://rdoc.info/projects/bkerley/affine

**Comment by zapnap** [comment]
Yes there seems to be a bug here (at least for this particular project). We'll look into it.

**Comment by zapnap** [comment]
Hmm this actually seems to be an issue with GitHub not building the pages when the named repo is pushed to. If you look at the docs.github.com repo, you'll see that the pages for the latter revision actually exist, but the public pages were never generated. Very strange. 

The docs.github.com stuff is still pretty experimental. It looks like we'll need to talk to The Powers That Be and see if there isn't some way to check / auto-request periodic page rebuilds from the repo I suppose...

**Comment by dreamcat4** [comment]
I've been seeing an issue whereby project isnt being generated 
http://docs.github.com/dreamcat4/libxml-bindings. (it is up on rdoc.info however). There is a hyphen in my project name, i don't know, but perhaps that that might be a reason? I can click on the grey square but it just says "generating..." "generating..."

**Comment by dreamcat4** [comment]
Actually... i've found its here http://github.com/docs/docs.github.com/tree/338f28709ffb8ce9e09d408246b0c86f81a55589/dreamcat4/libxml-bindings/blob/c4256c6bd2bfb6506311760b04bc40cf7ac91122 but the index.html is not mapped out to the access url http://docs.github.com/dreamcat4/libxml-bindings - we just see the search page.

**Comment by zapnap** [comment]
It looks to me like the appropriate index.html file exists in the docs.github.com repository -- http://github.com/docs/docs.github.com/blob/338f28709ffb8ce9e09d408246b0c86f81a55589/dreamcat4/libxml-bindings/index.html -- but that it isn't publicly available at http://docs.github.com/dreamcat4/libxml-bindings

Strange. Looks like the page just isn't getting "built" for some reason on the GH side and I'm not sure why :/. Might be time to file a ticket, I guess?

**Comment by zapnap** [comment]
Right now it looks like we are probably going to discontinue support of docs.github.com until pages are a bit more reliable for 'large deploys' like this.
