### ISSUE TITLE
Not displaying generating info for a project correctly

### ISSUE THREAD

**Issue by jeffWelling** [zapnap/rdocinfo#24]
I noticed that it isn't generating documentation for my lib, http://rdoc.info/projects/jeffWelling/libthetvdb  properly.   I did just create it, but I didn't have to wait for it to work properly before.  Does it not work on lib*.rb files?
It shows one file, README.  There are at least 3 others though, COPYING, HEADER, and libthetvdb.rb .
Cheers

**Comment by zapnap** [comment]
You need to add a .document file (or yardopts) to specify which files to index. See the text at the bottom of http://rdoc.info/projects/new. That file should look something like:

README
COPYING
HEADER
libthevdb.rb

Thanks!

**Comment by jeffWelling** [comment]
Ah, didn't notice that.
I noticed it worked for my other projects which was confusing because this one didn't but after looking, its because my other projects conform to the default at the bottom of that link.  I hadn't noticed it until just now.
Thanks!

**Comment by zapnap** [comment]
No prob, thanks for using rdoc.info!
