### ISSUE TITLE
Docs not being generated for new project grempe/opensecrets

### ISSUE THREAD

**Issue by grempe** [zapnap/rdocinfo#25]
I added a post commit hook on GitHub for a new project created today grempe/opensecrets.

I am unable to get the project to generate yardocs on your site.

If I visit:

http://rdoc.info/projects/grempe/opensecrets

I am asked to submit the username and project name.  Doing so generates a 'Something Bad Happened' (likely 500) error page.

Can you help me out?  I'd love to get the docs posted today.

**Comment by zapnap** [comment]
Was the result of a temporary problem on our production server. Should be fixed now, sorry about that.

**Comment by grempe** [comment]
All fixed.  Thanks.
