### ISSUE TITLE
Updating branch gh-pages blanks documentation

### ISSUE THREAD

**Issue by wedesoft** [zapnap/rdocinfo#29]
Hi,
The documentation at http://rdoc.info/projects/wedesoft/malloc becomes a blank page when I push a commit to the "gh-pages" branch of the project in order to update the Github project page http://wedesoft.github.com/malloc/ . After pushing a change to the "master" branch the documentation at http://rdoc.info/projects/wedesoft/malloc comes back.

**Comment by zapnap** [comment]
Rdoc.info now _only_ tracks the master branch, so this won't happen. I've been thinking about creating optional support to track more than one branch through some URL scheme but this definitely covers the most common case. 

Another option would be allowing the default branch ref to be specified in the .document file, maybe. I'll open another issue for it; feel free to comment there if you have an opinion about it.

**Comment by wedesoft** [comment]
Thanks
