### ISSUE TITLE
yardoc not generating - problem with yardopts

### ISSUE THREAD

**Issue by markevans** [zapnap/rdocinfo#31]
Hi there!

Is there any way of finding out what is wrong with my project at
http://rdoc.info/projects/markevans/dragonfly ?

It generates fine locally on my machine

Many thanks

Mark

**Comment by zapnap** [comment]
Hi Mark,

The issue is that our custom version of YARD doesn't support the -e switch for security reasons. I probably should have modified it to just not execute that code instead of removing the option entirely.

**Comment by markevans** [comment]
I see - thanks for getting back.
Does that mean there's no way of using custom YARD handlers?
Thanks

**Comment by zapnap** [comment]
With rdoc.info it does, yes (at least for now, open to suggestions /  patches). That would allow arbitrary code execution, which would open us up to a possible compromise without a proper sandbox.

**Comment by markevans** [comment]
Right - makes sense.
Cheers
Mark
