### ISSUE TITLE
coughing blood on marekj-watir but locally yardoc works

### ISSUE THREAD

**Issue by ghost** [zapnap/rdocinfo#34]
project
http://github.com/marekj/watir/
when I pass commit 80219c7a75caa5ec5b05b179455fcf2fa3b1f29f
rdoc.info coughs blood
as you can see here
http://github.com/marekj/watir/blob/rdocfix/.yardopts
project is non standard. it has source for 3 gems inside: watir, commonwatir and firewatir.
I am putting globs to *.rb files per my understanding of yardoc
and the yardoc generation works locally by running yardoc with no extra options on cli.
here is my output on my server: 
http://rubytester/test/watir/yardoc
I am clueless what to do next
thanks
(I tried on http://yardoc.org/docs/marekj-watir and nothing was generated there either)

**Comment by zapnap** [comment]
It looks like your default branch isn't master but is 'rdocfix'? Right now we don't support non-master branch generation, so that'd most likely be the issue.

**Comment by zapnap** [comment]
resolved this issue off-list.

**Comment by ghost** [comment]
Thanks. We are almost there. 
I reset github to point to master as master (and merged feature into master)
The new issues is that README contents are not displayed, should I write a new issue? Thanks
All else seems to be ok.
