### ISSUE TITLE
RDoc generation going on for more than 12 hours for RubyTree project

### ISSUE THREAD

**Issue by evolve75** [zapnap/rdocinfo#35]
Hi,

I tried to refresh the rdoc documentation for my github project - RubyTree (http://github.com/evolve75/RubyTree) yesterday after pushing a new commit (commit: a51d9e6832cd46a75a47a6bb0b694df6115ec860).

However, rdoc.info (http://rdoc.info/projects/evolve75/RubyTree) is still displaying the message "Generating Documentation" after more than 12 hours.

Help!

**Comment by zapnap** [comment]
I'll take a look this evening and see if I can nail down exactly what the problem was. In the meantime, I've manually regenerated it for you. Should be available at the usual URL. Apologies for the inconvenience.

**Comment by evolve75** [comment]
Thanks!  The manually regenerated version is perfectly fine.

Will keep this issue open for you to track the root cause as you have mentioned.

**Comment by zapnap** [comment]
I believe this should be working now. Feel free to open a new issue if similar problems occur.

**Comment by evolve75** [comment]
Thanks!  Will check and let you know.
