### ISSUE TITLE
rdoc.info does not honor the #-- and #++ Rdoc switches for temporarily turning off the doc generation

### ISSUE THREAD

**Issue by evolve75** [zapnap/rdocinfo#36]
Hi,

It appears that rdoc.info does not honor the following RDoc switch usage for temporarily turning off the documentation generation. E,g,

 # My documentation here ... blah blah blah
 # Some more
 #
 #-- 
 # The previous line should have turned off documentation generation for the subsequent  section.
 # Usually this is where a developer puts internal TODOs etc.
 # The next line should turn on the documentation generation again
 #++

What this means is that documentation I wrote for myself (TODOs etc) and not meant for the user to see are not getting listed in the rdoc.info pages!

Help!

**Comment by evolve75** [comment]
Dang.  The comment submission system is reading the formatting as markdown.  So another try.  the switches are:

   #--

and #++

**Comment by zapnap** [comment]
We use YARD rather than "old school" Rdoc to generate Ruby library documentation: http://github.com/lsegal/yard I believe that particular decision was intentional, but I can't speak to it personally.

**Comment by evolve75** [comment]
Wow!

That was a fast response!  Thanks for the clarification.  I have posted the query on the YARD mailing list (as a wish list item).

Thanks again!
