### ISSUE TITLE
yard syntax error

### ISSUE THREAD

**Issue by chikamichi** [zapnap/rdocinfo#39]
Hi.

I encounter a problem using yardoc for the project http://github.com/chikamichi/metamorphosis

<pre><code>
$ rake yard
(in /home/jd/dev/ruby/metamorphosis)
[warn]: Syntax error in `todo`:(3,20): syntax error, unexpected tidentifier, expecting keyword_do or '{' or '('
[warn]: Syntax error in `license`:(2,44): syntax error, unexpected tinteger, expecting keyword_do or '{' or '('
[warn]: Syntax error in `version`:(1,3): no .<digit> floating literal anymore; put 0 before dot
[warn]: Syntax error in `readme.md`:(7,10): syntax error, unexpected tidentifier, expecting keyword_do or '{' or '('
</code></pre>

Did anyone run into this already?

**Comment by lsegal** [comment]
This is not a bug. You are telling YARD to try and parse your readme documents as Ruby source files. Remove the non-Ruby-source-files from your .document and you should no longer get those warnings.

**Comment by chikamichi** [comment]
Thank you very much :)
I added lib/*_/_.rb btw.

**Comment by zapnap** [comment]
Thanks Loren!
