### ISSUE TITLE
Fails hard on iPad

### ISSUE THREAD

**Issue by jbarnette** [zapnap/rdocinfo#41]
Load any reasonably long page. Scrolling is totally busted for me.

**Comment by jeffrafter** [comment]
Can you maybe give some reasonable detail here? What part is busted? Is the scrollbar gone, does it not scroll long enough? Can you send us a screenshot?

**Comment by jbarnette** [comment]
I think it's probably safe to close this issue! Sorry about the terrible bug report, IIRC I was having a hard time learning how to type on that same iPad. 😆
