### ISSUE TITLE
Could not create new project at rdoc.info

### ISSUE THREAD

**Issue by imanel** [zapnap/rdocinfo#42]
From three days I'm trying to create rdoc for my projects at github, and every time it shows 'Something Bad Happened' error message. Is it something with server or I have something inside code that breaks rdoc.info?

**Comment by zapnap** [comment]
Can you please supply the repo name you're having trouble with? If you can do that I'll take a look later today. Thanks.

**Comment by imanel** [comment]
I'm trying any repo:
imanel / white_list_model (empty commit)
imanel / socky_plugin (empty commit)
imanel / socky_gem (empty commit)
imanel / socky_gem (commit bf2cbaf08c6ad456e3bd)
None of them are working.
I've tryed use service hooks(github -> administration -> service hooks -> rdocinfo)
First I clicked "test hook" and it shown "Payload deployed" and after that I clicked "update settings" and it shown "Service settings saved successfully!" - there were a few commits after setting that so I think that it should be created now...

**Comment by zapnap** [comment]
This should be fixed now :). Sorry for the temporary inconvenience. I regenerated docs for your project socky_gem and they should auto-update when you push from now on. As soon as you push a commit to github from your other projects those should be auto-created as well.

http://rdoc.info/projects/imanel/socky_gem
