### ISSUE TITLE
Better method rendering

### ISSUE THREAD

**Issue by ghost** [zapnap/rdocinfo#43]
While I like rdoc.info overall, there is one part that really irks me -- they way methods are rendered.

The main thing is the '(Type)' return value listed before each one. This isn't Java. Ruby is dynamically typed, so most of the time that is simply meaningless. Rather than putting it before, put it after, as in

  foo_method  -> Boolean

And if it's just Object, don't put anything at all.

Also the '-'/'+' prefix. Pretty esoteric. How about a nice icon to distinguish them.

**Comment by zapnap** [comment]
rdoc.info uses YARD to generate project docs and a slightly-modified template for rendering. Fwiw, the method representation is stock. You might want to raise this as an issue with the YARD project if you feel strongly about it.

**Comment by ghost** [comment]
I posted the issue there. Thanks.
