### ISSUE TITLE
UTF8 not respected

### ISSUE THREAD

**Issue by Burgestrand** [zapnap/rdocinfo#46]
My code contains UTF8 (more specifically in the README) which shows up strange as there’s no content-type.

Is there a way to specify it, and if not — will there be? :)

**Comment by zapnap** [comment]
this should probably be the standard content-type; most likely an oversight :). I'll push an update as soon as I can find a few spare cycles. Thanks!

**Comment by Burgestrand** [comment]
Sweetness. Thank you!

**Comment by zapnap** [comment]
should be all set now. let me know if you have any other issues related to this. if you want something other than utf-8 (the default), you can specify it with yard's --charset option too.
