### ISSUE TITLE
Doesn't honour :nodoc:

### ISSUE THREAD

**Issue by jphastings** [zapnap/rdocinfo#48]
Example in my [Tesco Groceries](http://rdoc.info/projects/jphastings/TescoGroceries) rdoc, have a look at the Offer class's constructor source.

**Comment by zapnap** [comment]
rdoc.info uses YARD, which does not support :nodoc: on purpose. You may want to consider using @private. See http://groups.google.com/group/yardoc/browse_thread/thread/d18febede98b3b63?pli=1
