### ISSUE TITLE
Generate docs for different branches / tags / releases?

### ISSUE THREAD

**Issue by zapnap** [zapnap/rdocinfo#5]
Right now we just track documentation for the master branch of any given project on GitHub. We could potentially add a way to track and generate docs for different branches, tags, etc. That way you could have, say, rdocs hosted for both Rails 2.2 and 2.3, etc.

**Comment by jeffrafter** [comment]
We should probably generate based on commit SHA. Then push all of the items into the subdir like Github does. Then we can create a list of generated docs at the owner/project/index.html

**Comment by zapnap** [comment]
Agreed. I like what you're doing with the redirect-to-most-recent-hash for the .info-side site. But how to handle this for the static docs variant? (or is this already worked out) Maybe we can maintain an index of generated docs as a popup / toolbar?
